[[main]]
  name = "Machines"
  url = "/machines/"
  weight = 20

[[Machines]]
  name = "Denford Laser Cutter"
  url = "/machines/denfordlasercutter/"
  weight = 10

[[main]]
  name = "What Am I?"
  url = "/whatami/"
  weight = 10

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
