[[main]]
  name = "Machines"
  url = "/machines/"
  weight = 20


[[main]]
  name = "What Am I?"
  url = "/what-am-i/"
  weight = 10

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
